### PR TITLE
fix(bitcoind): return setup_bitcoind error

### LINKED ISSUE #29: FIx antipattern exit(1) in src/bitcoind/actions.rs
`setup_bitcoind` should just return a BitcoindError

### PR DESCRIPTION
**Pull request by edouardparis**
close #29

(I had the commit in a PR, just cherry-picked it)

### CODE REVIEW

**Comment by darosior** [comment]
Nice.
 diff looks ok, will check and merge tomorrow

File: src/main.rs [hunk 1]
```diff
@@ -29,26 +29,28 @@ fn parse_args(args: Vec<String>) -> Option<PathBuf> {
...
     // We poll bitcoind until we die
-    bitcoind_main_loop(&mut revaultd, &bitcoind).unwrap_or_else(|e| {
+    bitcoind_main_loop(&mut revaultd, &bitcoind).map_err(|e| {
         log::error!("Error in bitcoind main loop: {}", e.to_string());
-        process::exit(1)
-    });
+        e
+    })?;
+
+    Ok(())
```
Comment (darosior) [inline src/main.rs:53]: I think it's cleaner to exit(1) here in case of error.
Returning a Result here is just going to make our life harder with https://github.com/re-vault/revaultd/commits/jsonrpc_interface2 , i think.

File: src/bitcoind/mod.rs [hunk 2]
```diff
@@ -9,3 +9,5 @@ impl std::fmt::Display for BitcoindError {
         write!(f, "Bitcoind error: {}", self.0)
     }
 }
+
+impl std::error::Error for BitcoindError {}
```
Comment (darosior) [inline src/bitcoind/mod.rs:13]: medumb

File: src/bitcoind/actions.rs [hunk 3]
```diff
@@ -223,37 +223,39 @@ fn maybe_load_wallet(revaultd: &RevaultD, bitcoind: &BitcoinD) -> Result<(), Bit
...
+
+    maybe_load_wallet(&revaultd, &bitcoind).map_err(|e| {
         log::error!("Error while loading wallet: {}", e.to_string());
-        process::exit(1);
-    });
+        e
+    })?;
 
-    bitcoind
+    Ok(bitcoind)
```
Comment (darosior) [inline src/bitcoind/actions.rs:258]: Can we log only once in the caller ?
I.e for the first line:
```rust
let bitcoind = BitcoinD::new(&revaultd.bitcoind_config).map_err(|e| {
        log::error!("Could not connect to bitcoind: {}", e.to_string());
        process::exit(1);
        e
    });
})?;
```
====>
```rust
let bitcoind = BitcoinD::new(&revaultd.bitcoind_config).map_err(|e|
        BitcoindError(format(""Could not connect to bitcoind: {}", e.to_string()))
    });
})?;
```

So that in main we can do:
```rust
let bitcoind = setup_bitcoind(&mut revaultd).unwrap_or_else(|e| {
    log...
    exit...
});

File: src/main.rs [hunk 4]
```diff
@@ -29,26 +29,28 @@ fn parse_args(args: Vec<String>) -> Option<PathBuf> {
...
     // First and foremost
-    setup_db(&mut revaultd).unwrap_or_else(|e| {
+    setup_db(&mut revaultd).map_err(|e| {
         log::error!("Error setting up database: '{}'", e.to_string());
-        process::exit(1)
-    });
+        e
+    })?;
 
     // This aborts on error
```
Comment (darosior) [inline src/main.rs:39]: You can also remove this comment, this doesn't abort anymore on error.

**Review by darosior — COMMENTED** [review]
Actually, i have a few requests

File: src/main.rs (hunk 1 above)
Comment (edouardparis) [reply src/main.rs:53]: link give me 404

Comment (darosior) [reply src/main.rs]: Edited, this refered to the branch in #23 ..

**Review by darosior — APPROVED** [review]
ACK a94ba5c
